kind: pipeline
name: default

services:
- name: mysql_db
  image: mysql
  ports:
  - 3306
  environment:
    MYSQL_PASSWORD: ln1234
    MYSQL_DATABASE: meta
    MYSQL_ROOT_PASSWORD: ln1234_root
    MYSQL_USER: luke
  # Fix Chinese garbled
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  

steps:
- name: Create Table
  image: mysql
  commands:
  - sleep 15
  - mysql -u root -pln1234_root  -h mysql_db --execute="CREATE TABLE meta.provider (id varchar(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"

- name: Use different image and Create Database
  image: mysql:5.7.22
  commands:
  - sleep 10
  - mysql -u root -proot123456  -h mysql --port=3306 --execute="CREATE DATABASE line_cms;"