kind: pipeline
name: default

services:
- name: mysql_db
  image: mysql
  ports:
  - 3306
  environment:
    MYSQL_PASSWORD: ln1234
    MYSQL_DATABASE: meta
    MYSQL_ROOT_PASSWORD: ln1234_root
    MYSQL_USER: luke

steps:
- name: setup MySQL DB
  image: mysql
  commands:
  - sleep 15
  - mysql -u root -pln1234_root  -h mysql_db --execute="CREATE TABLE meta.provider (id varchar(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"