kind: pipeline
name: default

services:
- name: redis
  image: redis
  ports:
  - 6379
  command:
  - "--requirepass admin"



steps:
- name: ping redis
  image: redis
  commands:
  - sleep 5
  - redis-cli -h redis -a admin ping #PONG
  - redis-cli -h redis -a admin set FOO bar
  - redis-cli -h redis -a admin get FOO